### ISSUE TITLE
Following error on attempted install

### ISSUE THREAD

**Issue by pebblexe** [3b/clws#13]
Subprocess (:PROCESS #<SB-IMPL::PROCESS :EXITED 1>
            :OUTPUT-STREAM
            #<SB-SYS:FD-STREAM for "descriptor 7" {1008AA6543}>)
 with command ("g++" "-m64" "-Wno-write-strings"
               "-I/home/k/quicklisp/dists/quicklisp/software/iolib-v0.8.1/src/grovel/"
               "-o"
               "/home/k/.cache/common-lisp/sbcl-1.3.3.debian-linux-x64/home/k/quicklisp/dists/quicklisp/software/iolib-v0.8.1/src/syscalls/ffi-types-unix"
               "/home/k/.cache/common-lisp/sbcl-1.3.3.debian-linux-x64/home/k/quicklisp/dists/quicklisp/software/iolib-v0.8.1/src/syscalls/ffi-types-unix.c")
 exited with error code 1
   [Condition of type UIOP/RUN-PROGRAM:SUBPROCESS-ERROR]

Restarts:
 0: [CONTINUE] IGNORE-ERROR-STATUS
 1: [RETRY] Retry PROCESS-OP on #<GROVEL-FILE "iolib/syscalls" "ffi-types">.
 2: [ACCEPT] Continue, treating PROCESS-OP on #<GROVEL-FILE "iolib/syscalls" "ffi-types"> as having been successful.
 3: [RETRY] Retry ASDF operation.
 4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 5: [ABORT] Give up on "bitsforsale"
 --more--

Backtrace:
  0: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND ("g++" "-m64" "-Wno-write-strings" "-I/home/k/quicklisp/dists/quicklisp/software/iolib-v0.8.1/src/grovel/" "-o" "/home/k/.cache/common-lisp/sbcl-1.3.3.debia..
  1: ((FLET #:CLEANUP-FUN-8071 :IN UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM)) [cleanup]
  2: ((LAMBDA (UIOP/RUN-PROGRAM::REDUCED-INPUT UIOP/RUN-PROGRAM::INPUT-ACTIVITY) :IN UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM) NIL NIL)
  3: (UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM ("g++" "-m64" "-Wno-write-strings" "-I/home/k/quicklisp/dists/quicklisp/software/iolib-v0.8.1/src/grovel/" "-o" "/home/k/.cache/common-lisp/sbcl-1.3.3.debian-linux-..
  4: (IOLIB/GROVEL::INVOKE #<unavailable argument> "-m64" "-Wno-write-strings" "-I/home/k/quicklisp/dists/quicklisp/software/iolib-v0.8.1/src/grovel/" "-o" "/home/k/.cache/common-lisp/sbcl-1.3.3.debian-lin..
  5: ((LAMBDA NIL :IN IOLIB/GROVEL:PROCESS-GROVEL-FILE))

**Comment by 3b** [comment]
Looks like [iolib](https://github.com/sionescu/iolib) (the networking library used by clws) failed to load. Possibly you need to install the C library `libfixposix` used by iolib, or if you don't compile C things much it could be other libs or even the compiler itself that is missing.

**Comment by pebblexe** [comment]
That was it! Thank you.
